### ISSUE TITLE
jQuery v3.1.1 Compatibility issue SOLVED

### ISSUE THREAD

**Issue by jh-thank-you** [beezee/djax#46]
I know djax is old and more thank likely not being supported but for what it is worth, for any other newbie out there like me, this seems to be working fine with the latest jQuery v3.1.1 with a small change.

You will need to change ".error" to ".fail" on line 212 (two hundred twelve) of the jquery.djax.js file. If you don't the console will give an error, stating that "Unexpected Token... .error is not a function..."

For some reason the  jQuery Migration Plugin does not seem to be working for me... but reading through the warnings list I was able to figure out how to solve the issue.

Taken from the jQuery Migration Guide found at 
[https://github.com/jquery/jquery-migrate/blob/master/warnings.md](url)

**To Beezee - Thank you!!** for creating and sharing this. Also, if you have advice that I should use another solution I'm all ears... I looked into PJAX, DDJAX, TurboLinks, AngularJS (too much for my needs) etc. -  djax seemed the easiest to implement. If there is a more current fork/branch of this please advise. Thanks in Advance for any help or guidance you may provide.
